newSource1.scala:5: error: macro error!
  AlwaysError.summonError
              ^